apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-python
spec:
  replicas: 3
  selector:
    matchLabels:
      app: myapp-python
  template:
    metadata:
      labels:
        app: myapp-python
    spec:
      containers:
        - name: app-container
          image: osayman74/python-app
          ports:
          - containerPort: 81
---
apiVersion: v1
kind: Service
metadata:
  name: myapp-service
spec:
  type: LoadBalancer
  selector:
    app: myapp-python
  ports:
  - protocl: TCP
    port: 81
    targetPort: 81

