apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-python
  labels:
    app: myapp
    type: front-end
spec:
  template:
    metadata:
      name: myapp-pod
      labels:
        app: myapp
        type: front-end
    spec:
      containers:
        - name: app-container
          image: docker.io/osayman74/python-app
  replicas: 3
  selector: 
    matchLabels:
      type: front-end
