apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2024-04-18T19:09:55Z"
  labels:
    app: myapp
    type: front-end
  name: myapp-python
  namespace: default
  resourceVersion: "4055"
  uid: 22b9c410-8855-44b2-b372-2ca004efd023
spec:
  clusterIP: 10.100.19.120
  clusterIPs:
  - 10.100.19.120
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    type: front-end
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}